[package]
name = "coreos-metadata"
version = "1.0.6"
authors = ["Stephen Demos <stephen.demos@coreos.com>"]

[[bin]]
name = "coreos-metadata"
path = "src/bin/coreos-metadata.rs"

[profile.release]
lto = true

[features]
default = ["azure", "digitalocean", "cloudstack", "ec2", "gce", "openstack", "packet",
"vagrant_virtualbox"]

azure = ["openssl", "serde-xml-rs"]
digitalocean = []
cloudstack = []
ec2 = []
gce = []
openstack = []
packet = []
vagrant_virtualbox = []

[dependencies]
clap = "2.26"
users = "0.6"
slog-term = "2.2"
slog-async = "2.1"
slog-scope = "4.0"
mime = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde-xml-rs = { version = "0.2", optional = true }
serde_json = "1.0"
openssl = { version = "0.9.17", optional = true }
base64 = "0.9"
byteorder = "1.1"
pnet = "0.21"
reqwest = "0.7"
hyper = "0.11"
error-chain = { version = "0.12", default-features = false }
openssh-keys = "0.3"
update-ssh-keys = { git = "https://github.com/coreos/update-ssh-keys", tag = "v0.2.0" }
ipnetwork = "0.12"
hostname = "0.1"
tempdir = "0.3"
nix = "0.9"

[dependencies.slog]
version = "2.0"
features = ["max_level_trace", "release_max_level_info"]

[dev-dependencies]
mockito = "0.9"
